blank_issues_enabled: false
contact_links:
  - name: Pokemon Heart and Soul's Discord server!
    url: https://discord.gg/4gVEygWChs
    about: You can follow the development of pokehns-expansion and be notified of new releases :)
