name: CI

on:
  push:
    branches:
      - main
      - development-bugfix
  pull_request:

jobs:
  build:
    if: github.actor != 'allcontributors[bot]'
    runs-on: ubuntu-latest
    env:
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: ROM (HnS)
        env:
          COMPARE: 0
        run: |
          make clean
          make -j${nproc} -O

      - name: LTO (HnS)
        env:
          GAME_VERSION: HEARTGOLD
        run: |
          make tidy
          make -j${nproc} LTO=1
        # make tidy to purge previous build

      ### Reintroduce once Emerald capability is restored
      #- name: ROM (Emerald)
      #  env:
      #    COMPARE: 0
      #    GAME_VERSION: EMERALD
      #  run: make emerald -j${nproc} -O all

      #- name: LTO (Emerald)
      #  env:
      #    GAME_VERSION: EMERALD
      #  run: |
      #    make tidy
      #    make -j${nproc} LTO=1
      #  # make tidy to purge previous build

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} check
